addons:
  hosts:
    - fluentkit.app
    
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - mysql -e 'create database homestead;' -uroot
  - mysql -e 'CREATE USER "homestead"@"localhost" IDENTIFIED BY "secret";' -uroot
  - mysql -e 'GRANT ALL PRIVILEGES ON *.* TO "homestead"@"localhost" WITH GRANT OPTION;' -uroot
  - travis_retry composer self-update
  - travis_retry composer install
  - travis_retry php artisan --env=local migrate

script: php artisan --env=local test

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true